### ISSUE TITLE
Cannot mock VueSweetalert2 with jest

### ISSUE THREAD

**Issue by ogomaemmanuel** [avil13/vue-sweetalert2#112]
I keep  getting 
 ``` SyntaxError: Cannot use import statement outside a module```
on `import VueSweetalert2 from 'vue-sweetalert2`

**Comment by avil13** [comment]
![image](https://user-images.githubusercontent.com/1606172/93762478-4e391580-fc18-11ea-9a58-e58856cb22e8.png)

**Comment by ogomaemmanuel** [comment]
● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\USER\IdeaProjects\vue_starter\node_modules\vue-sweetalert2\src\index.js:3
    import swal from 'sweetalert2/dist/sweetalert2.min.js';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import {createLocalVue, mount} from "@vue/test-utils"
      2 | import RoleCreateForm from "../RoleCreateForm";
    > 3 | import VueSweetalert2 from 'vue-sweetalert2';
        | ^
      4 | let localVue=createLocalVue();
      5 | localVue.use(VueSweetalert2)
      6 | jest.mock("axios");

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1179:56)
      at Object.<anonymous> (src/main/resources/static/js/src/components/access_control/roles/__test_/RoleCreateForm.spec.js:3:1)

**Comment by ogomaemmanuel** [comment]
import {createLocalVue, mount} from "@vue/test-utils"
    import RoleCreateForm from "../RoleCreateForm";
    import VueSweetalert2 from 'vue-sweetalert2';
    let localVue=createLocalVue();
    localVue.use(VueSweetalert2)
    jest.mock("axios");
    axios.post.mockResolvedValue({
        data: {}
    });

    Object.defineProperty(window, 'axios', {value: axios})
    describe('Role Create Form', () => {
    it("clicking create button should send data to the backend", async () => {
        localVue.swal({
            title:""

        })
        const wrapper = mount(RoleCreateForm, {
            localVue,
            data: function () {
                return {
                    role: {
                        name: "Test Role",
                        description: "Description"
                    }
                }
            }
        })

        await wrapper.findComponent({ref: "createButton"}).trigger('click');
        await wrapper.vm.$nextTick();
        console.log(  wrapper.vm.$swal().isVisible());
        //console.log(button.html());
        expect(axios.post).toBeCalledTimes(1);



        })
    })

**Comment by ogomaemmanuel** [comment]
take make my test pass for now, I had to move your index.js file to some folder and modify it just for test, this is how it looks like, I have removed the import keywords and using require instead. There is where we have a problem I guess

    // @ts-check
    /** @type swal {import("sweetalert2")} */
    const swal= require ('sweetalert2/dist/sweetalert2.min.js');

    function isBrowser() {
        return typeof window !== 'undefined';
    }

    var VueSweetalert2 = function () {};


    VueSweetalert2.install = function (Vue, options) {
    // adding a global method or property
    var _swal;

    if (isBrowser()) {
        _swal = (options ? swal.mixin(options) : swal);
    } else {
        _swal = function () {
            return Promise.resolve();
        };
    }

    Vue.swal = _swal;

    // add the instance method
    if (!Vue.prototype.hasOwnProperty('$swal')) {
        Object.defineProperty(Vue.prototype, '$swal', {
            get: function get() {
                return _swal
            }
        });
       }
    };

     export default VueSweetalert2;

**Comment by avil13** [comment]
The problem here is not the library.
The problem is that jest does not want to transpile sweatalert2 as dependencies.

**Comment by avil13** [comment]
If you want to solve the problem faster, you can use sweataler2 without a wrapper.

**Comment by avil13** [comment]
Since there is no activity, I am closing this issue.
