### ISSUE TITLE
Cannot read properties of undefined (reading 'options')  in Nuxt3 project with Yarn 

### ISSUE THREAD

**Issue by Metalzoid** [avil13/vue-sweetalert2#162]
Hello ! 

I tryed to install vue-sweetalert2 for my project in nuxt3 with Yarn.
```powershell
yarn add vue-sweetalert2
``` 
I get this error : 

```powershell
Cannot read properties of undefined (reading 'options')                                                                                                                       5:12:08 PM

  at nuxtVueSweetalert2 (node_modules/vue-sweetalert2/nuxt/index.mjs:5:42)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:2478:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4493:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4660:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2664:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1777:7) 

 ERROR  Cannot read properties of undefined (reading 'options')                                                                                                                       5:12:08 PM

error Command failed with exit code 1.
```

my nuxt.config.ts: 
```typescript
export default defineNuxtConfig({
  compatibilityDate: "2024-04-03",
  devtools: { enabled: true },
  modules: ["@nuxt/ui", "@pinia/nuxt", "@nuxt/image", "vue-sweetalert2/nuxt"],
  runtimeConfig: {
    public: {
      ADMIN_API_KEY: process.env.ADMIN_API_KEY,
      apiBase: process.env.API_BASE_URL,
    },
  },
  build: {
    transpile: ["@vuepic/vue-datepicker"],
  },
  css: ["@fortawesome/fontawesome-svg-core/styles.css"],
  imports: {
    dirs: [
      "composables",
      "composables/*/index.{ts,js,mjs,mts}",
      "composables/**",
    ],
  },
});
``` 

my stack : 

- Nuxt 3.13.1
- nuxtUI
- nuxtImage
- Pinia for nuxt
- Tailwind SCSS
- vite 5.4.4

I'm junior in development, forgive me if I didn't do the right thing.

**Comment by avil13** [comment]
Hi.
No module has been added for Nuxt3. 
I think I should remove it from the description. Sorry.

But actually, it's easiest for you to work with sweetalert2 directly, without wrapper. Api will not change much.
